### ISSUE TITLE
多个html页面不在同一级目录下，能否实现用一个path下的语言properties文件

### ISSUE THREAD

**Issue by LindaUnique** [FloweringVivian/jquery.i18n.properties#1]
`jQuery.i18n.properties({
    name : 'message', 
   path : 'i18n/', //资源文件路径
    mode : 'map'
`})

**Comment by LindaUnique** [comment]
已解决。path设置了动态传入

**Comment by Meijjj** [comment]
怎么动态传入呢 能否说一下呀
